// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YarnShop.Infrastructure.Repositories;

namespace YarnShop.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("YarnShop.Core.Domain.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("YarnShop.Core.Domain.Kit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Pattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToolId")
                        .HasColumnType("int");

                    b.Property<int>("n")
                        .HasColumnType("int");

                    b.Property<int?>("yarnTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.HasIndex("yarnTypeId");

                    b.ToTable("Kit");
                });

            modelBuilder.Entity("YarnShop.Core.Domain.KnittingNeedle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Circular")
                        .HasColumnType("bit");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int>("n")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KnittingNeedle");
                });

            modelBuilder.Entity("YarnShop.Core.Domain.YarnBundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("PricePercentage")
                        .HasColumnType("float");

                    b.Property<int?>("YarnTypeId")
                        .HasColumnType("int");

                    b.Property<int>("n")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YarnTypeId");

                    b.ToTable("YarnBundles");
                });

            modelBuilder.Entity("YarnShop.Core.Domain.YarnType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<double>("NeedlesSize")
                        .HasColumnType("float");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("YarnType");
                });

            modelBuilder.Entity("YarnShop.Core.Domain.Kit", b =>
                {
                    b.HasOne("YarnShop.Core.Domain.KnittingNeedle", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId");

                    b.HasOne("YarnShop.Core.Domain.YarnType", "yarnType")
                        .WithMany()
                        .HasForeignKey("yarnTypeId");

                    b.Navigation("Tool");

                    b.Navigation("yarnType");
                });

            modelBuilder.Entity("YarnShop.Core.Domain.YarnBundle", b =>
                {
                    b.HasOne("YarnShop.Core.Domain.YarnType", "YarnType")
                        .WithMany()
                        .HasForeignKey("YarnTypeId");

                    b.Navigation("YarnType");
                });

            modelBuilder.Entity("YarnShop.Core.Domain.YarnType", b =>
                {
                    b.HasOne("YarnShop.Core.Domain.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.Navigation("Color");
                });
#pragma warning restore 612, 618
        }
    }
}
